### ISSUE TITLE
Switch to Getthermostatsdata, Gethomedata and Getstationsdata by November 30th

### ISSUE THREAD

**Issue by wep4you** [cbornet/netatmo-swagger-decl#12]
I got this info today:

Friendly reminder: Getthermstate, Getuser and Devicelist will move from deprecated to shut down. On November 30th, we are proceeding to a structural change to make our APIs faster and more powerful. Unfortunately, old and deprecated API methods won’t be supported anymore. Make sure you amend your code and start using newer methods as soon as possible for a smooth transition:

Replace Getthermstate with Getthermostatdata
Replace Getuser with Getthermostatdata, Gethomedata or Getstationsdata
Replace Devicelist with Getthermostatdata or Getstationsdata

So it looks like, there are some updates required.

I already implemented the netatmo welcome

**Comment by cbornet** [comment]
Thanks for the notice.We already have the new methods.
Getthermstate, Getuser and Devicelist are marked as "deprecated". Once Neattmo shuts them down it will be easy to remove them

**Comment by cbornet** [comment]
I hope openHAB uses the new methods.
cc @clinique

**Comment by wep4you** [comment]
I already spend a Issue on Openhab2-addons for this, so if all is in the api, i could close this issue here?

**Comment by cbornet** [comment]
We can keep it to remember to remove the old ones.

**Comment by clinique** [comment]
@cbornet , yes I made the switching
