### ISSUE TITLE
Change NAPlug.plug_connected_boiler field from boolean to int

### ISSUE THREAD

**Issue by IOOOTAlan** [cbornet/netatmo-swagger-decl#17]
As mentioned in #15, it seems that the `NAPlug.plug_connected_boiler` field needs to change from boolean to int, too.
I performed some tests on the Netatmo openhab2 binding and I kept getting conversion errors with gson upon thing creation (Netatmo API) until I changed it too.
Maybe @clinique can also confirm this.

**Comment by cbornet** [comment]
@clinique do you confirm ?
@IOOOTAlan would you do a PR for this ?

**Comment by clinique** [comment]
@cbornet, yes I confirm, I discovered yesterday that existed a second plug_connected_boiler in the json file and my last PR adressed only the first one. Will push an updated.

**Comment by cbornet** [comment]
Fixed by #18
