### ISSUE TITLE
Implement new Presence camera event API extension

### ISSUE THREAD

**Issue by Novanic** [cbornet/netatmo-swagger-decl#25]
The Presence (outdoor) camera uses sub events. These are available via .../events/[i]/event_list/...

The "event_list" element is currently missing in this project.

**Comment by cbornet** [comment]
Closed by #24

**Comment by Novanic** [comment]
> Closed by #24

Hi, thank you for reviewing and merging the pull-request. :-) Could you also release a new version of netatmo-swagger-api (generating the retrofit code) with the updated schema? I require it to support events of the Netatmo Presence camera for OpenHAB. Or should I prepare it by myself and sending a pull-request for a new version?

Thank you in advance and best regards :-)
