### ISSUE TITLE
Support for getting favorite stations

### ISSUE THREAD

**Issue by Crazyphil** [cbornet/netatmo-swagger-decl#28]
The [official documentation](https://dev.netatmo.com/apidocumentation/weather#getstationsdata) of `/getstationsdata` mentions the `get_favorites` parameter to add favorited stations from the public [Weathermap](https://weathermap.netatmo.com/) to the list of stations. This would allow querying data from stations not directly associated to the user's account.

Could you please add support for this parameter to the specification? Unfortunately, it is not clear to me whether setting the parameter to `true` will *only* return favorited stations or add them to own ones, and I don't have any devices to test this with.

**Comment by cbornet** [comment]
Closed by #29
